#!/usr/bin/env python3
"""
GSD Compatibility Layer - Makes GSD workflows work in environments without Task tool.

This script:
1. Reads GSD workflow definitions from .pi/gsd/workflows/
2. Replaces 'Task(...)' calls with inline execution instructions
3. Outputs modified workflows that work with standard pi tools

Usage:
  # Generate compatible version of a workflow
  python3 pi-gsd-compat.py validate-phase > /tmp/validate-phase-compat.md

  # Execute agent inline (when Task would be called)
  python3 pi-gsd-compat.py exec-agent gsd-nyquist-auditor <context.json

Environment: pi-coding-agent without Task spawning support
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

GSD_ROOT = Path(__file__).parent
WORKFLOWS_DIR = GSD_ROOT / "workflows"
AGENTS_DIR = GSD_ROOT / "agents"


def load_workflow(workflow_name: str) -> str:
    """Load a workflow definition."""
    workflow_file = WORKFLOWS_DIR / f"{workflow_name}.md"
    if not workflow_file.exists():
        # Try common variations
        for ext in [".md", ""]:
            alt = WORKFLOWS_DIR / f"{workflow_name}{ext}"
            if alt.exists():
                workflow_file = alt
                break
    if not workflow_file.exists():
        raise FileNotFoundError(f"Workflow not found: {workflow_name}")
    return workflow_file.read_text()


def load_agent(agent_name: str) -> dict[str, Any]:
    """Load agent definition."""
    agent_file = AGENTS_DIR / f"{agent_name}.md"
    if not agent_file.exists():
        raise FileNotFoundError(f"Agent not found: {agent_name}")

    content = agent_file.read_text()

    # Parse frontmatter
    agent_data = {"name": agent_name, "content": content}
    if content.startswith("---"):
        end = content.find("---", 3)
        if end > 0:
            fm = content[3:end].strip()
            for line in fm.split("\n"):
                if ":" in line and not line.startswith("#"):
                    key, val = line.split(":", 1)
                    agent_data[key.strip()] = val.strip().strip('"').strip("'")

    # Extract execution flow
    exec_match = re.search(
        r"<execution_flow>(.*?)</execution_flow>", content, re.DOTALL
    )
    agent_data["execution_flow"] = exec_match.group(1).strip() if exec_match else ""

    return agent_data


def replace_task_with_inline(workflow_content: str) -> str:
    """Replace Task(...) calls with inline execution instructions."""
    # Pattern to match Task(...) blocks
    task_pattern = r"Task\(\s*prompt=\"([^\"]*)\"[^)]*subagent_type=\"([^\"]*)\"[^)]*\)"

    def replacement(match):
        prompt = match.group(1).replace("\\n", "\n")
        agent_name = match.group(2)

        return f"""## 5. EXECUTE AGENT INLINE (Task tool unavailable)
**Agent:** {agent_name}
**Instructions:** Load agent definition from `.pi/gsd/agents/{agent_name}.md` and execute steps.

### Step 5a: Read Agent Definition
```bash
cat .pi/gsd/agents/{agent_name}.md
```

### Step 5b: Execute Agent Logic
Read the `<execution_flow>` from the agent definition and perform each step using your available tools.

### Step 5c: Capture Output
When complete, append to response:

**IF ALL GAPS RESOLVED:**
```markdown
## GAPS FILLED
All tests created successfully.
```

**IF SOME GAPS FAILED AFTER 3 RETRIES:**
```markdown
## PARTIAL
Resolved: N, Escalated: M
```

**IF CRITICAL ERROR:**
```markdown
## ESCALATE
Reason: [description]
```

*Note: This inline execution replaces Task() spawning which is unavailable in this environment.*"""

    return re.sub(task_pattern, replacement, workflow_content, flags=re.DOTALL)


def generate_compatible_workflow(workflow_name: str) -> str:
    """Generate a workflow compatible with this environment."""
    content = load_workflow(workflow_name)

    # Add compatibility header
    header = f"""<gsd-version v="1.30.0-compat" />
<!-- 
COMPATIBILITY NOTICE: This workflow has been modified for environments without Task tool.
Original: .pi/gsd/workflows/{workflow_name}.md
Generated by: pi-gsd-compat.py
-->

"""

    # Replace Task() calls
    modified = replace_task_with_inline(content)

    # Add footer
    footer = """
<!-- 
COMPLETED: Agent execution steps have been converted to inline instructions.
Perform each step using standard Read/Write/Edit/Bash tools as appropriate.
-->
"""

    return header + modified + footer


def exec_agent_inline(agent_name: str, context: dict[str, Any]) -> dict[str, Any]:
    """Execute an agent's logic inline (since Task() is unavailable)."""
    try:
        agent = load_agent(agent_name)
    except FileNotFoundError:
        return {"error": f"Agent not found: {agent_name}"}

    print("═══════════════════════════════════════════")
    print(f"AGENT: {agent.get('name', agent_name)}")
    print(f"DESCRIPTION: {agent.get('description', 'N/A')}")
    print("═══════════════════════════════════════════")
    print()
    print("Since Task() tool is unavailable, executing agent logic INLINE.")
    print("This means YOU (the AI) are now acting as the agent.")
    print()
    print("Follow the execution flow from the agent definition:")
    print()

    # Extract key instructions from execution flow
    exec_flow = agent.get("execution_flow", "")

    # Look for key steps
    steps = []
    for line in exec_flow.split("\n"):
        line = line.strip()
        if (
            line.startswith("<step")
            or line.startswith("## Step")
            or (line and line[0].isdigit() and "." in line[:3])
        ):
            steps.append(line)

    if steps:
        print("KEY STEPS:")
        for i, step in enumerate(steps[:10], 1):
            print(f"  {i}. {step[:80]}...")

    print()
    print("CONTEXT PROVIDED:")
    for key, val in context.items():
        if isinstance(val, str):
            print(f"  {key}: {val[:100]}...")
        else:
            print(f"  {key}: {type(val).__name__}")

    return {
        "status": "INLINE_EXECUTION",
        "agent": agent_name,
        "message": "Execute agent logic using your standard tools and return structured output",
        "steps": steps[:10],
    }


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        print("\nAvailable workflows:")
        for f in WORKFLOWS_DIR.glob("*.md"):
            print(f"  - {f.stem}")
        print("\nAvailable agents:")
        for f in AGENTS_DIR.glob("*.md"):
            print(f"  - {f.stem}")
        return 1

    command = sys.argv[1]

    if command == "exec-agent":
        if len(sys.argv) < 3:
            print("Usage: pi-gsd-compat.py exec-agent <agent-name> [context.json]")
            return 1

        agent_name = sys.argv[2]
        context = {}
        if len(sys.argv) > 3:
            try:
                with open(sys.argv[3]) as f:
                    context = json.load(f)
            except:
                pass

        result = exec_agent_inline(agent_name, context)
        print()
        print("RESULT:")
        print(json.dumps(result, indent=2))

    else:
        # Assume it's a workflow name
        workflow_name = command
        try:
            output = generate_compatible_workflow(workflow_name)
            print(output)
        except FileNotFoundError as e:
            print(f"Error: {e}", file=sys.stderr)
            return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
